Repository sopt-makers/sopt-auth-backend, pull requests merged in 2024-12, with the labels that each got.

#15 [FEAT] 번호 인증 검사 기능 구현
  .gitignore
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/main/java/sopt/makers/authentication/application/auth/api/AuthApiController.java
  src/main/java/sopt/makers/authentication/application/auth/dto/request/AuthRequest.java
  src/main/java/sopt/makers/authentication/application/auth/dto/response/AuthResponse.java
  src/main/java/sopt/makers/authentication/database/PhoneVerificationRepositoryImpl.java
  src/main/java/sopt/makers/authentication/database/UserRegisterInfoRepositoryImpl.java
  src/main/java/sopt/makers/authentication/database/UserRepositoryImpl.java
  src/main/java/sopt/makers/authentication/database/rdb/entity/UserRegisterInfoEntity.java
  src/main/java/sopt/makers/authentication/database/rdb/entity/auth/PhoneVerificationEntity.java
  src/main/java/sopt/makers/authentication/database/rdb/repository/PhoneVerificationJpaRepository.java
  src/main/java/sopt/makers/authentication/database/rdb/repository/PhoneVerificationRepositoryImpl.java
  src/main/java/sopt/makers/authentication/database/rdb/repository/UserJpaRepository.java
  src/main/java/sopt/makers/authentication/database/rdb/repository/UserRegisterInfoJpaRepository.java
  src/main/java/sopt/makers/authentication/database/rdb/repository/UserRegisterInfoRemover.java
  src/main/java/sopt/makers/authentication/database/rdb/repository/UserRegisterInfoRetriever.java
  src/main/java/sopt/makers/authentication/database/rdb/repository/UserRetriever.java
  src/main/java/sopt/makers/authentication/database/rdb/repository/auth/PhoneVerificationJpaRepository.java
  src/main/java/sopt/makers/authentication/database/rdb/repository/auth/PhoneVerificationRegister.java
  src/main/java/sopt/makers/authentication/database/rdb/repository/auth/PhoneVerificationRemover.java
  src/main/java/sopt/makers/authentication/database/rdb/repository/auth/PhoneVerificationRetriever.java
  src/main/java/sopt/makers/authentication/domain/auth/PhoneVerification.java
  src/main/java/sopt/makers/authentication/domain/auth/PhoneVerificationType.java
  src/main/java/sopt/makers/authentication/domain/user/UserRegisterInfo.java
  src/main/java/sopt/makers/authentication/support/code/domain/failure/AuthFailure.java
  src/main/java/sopt/makers/authentication/support/code/domain/failure/UserFailure.java
  src/main/java/sopt/makers/authentication/support/code/domain/success/AuthSuccess.java
  src/main/java/sopt/makers/authentication/support/common/api/BaseResponse.java
  src/main/java/sopt/makers/authentication/usecase/auth/port/in/VerifyPhoneVerificationUsecase.java
  src/main/java/sopt/makers/authentication/usecase/auth/port/out/PhoneVerificationRepository.java
  src/main/java/sopt/makers/authentication/usecase/auth/port/out/UserRepository.java
  src/main/java/sopt/makers/authentication/usecase/auth/service/CreateVerificationService.java
  src/main/java/sopt/makers/authentication/usecase/auth/service/VerifyVerificationService.java
  src/main/java/sopt/makers/authentication/usecase/user/port/out/UserRegisterInfoRepository.java
  src/test/java/sopt/makers/authentication/application/auth/api/AuthApiControllerTest.java
  src/test/java/sopt/makers/authentication/database/PhoneVerificationRepositoryImplTest.java
  src/test/java/sopt/makers/authentication/domain/auth/PhoneVerificationTest.java
  src/test/java/sopt/makers/authentication/usecase/auth/service/CreateVerificationServiceTest.java
  src/test/java/sopt/makers/authentication/usecase/auth/service/VerifyVerificationServiceTest.java
Labels: size/XL, 🎁 feature

#21 [Infra/#11] 무중단 배포 자동화 환경 구축 (Docker)
  .dockerignore
  .github/workflows/cd-dev.yml
  .github/workflows/cd-prod.yml
  .github/workflows/ci.yml
  .gitignore
  Dockerfile
  appspec.yml
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/sopt/makers/authentication/support/code/domain/failure/AuthFailure.java
  src/main/resources/application-dev.yaml
  src/main/resources/application-local.yaml
  src/main/resources/application-prod.yaml
  src/main/resources/application-test.yaml
  src/main/resources/external.yaml
  src/main/resources/jwt.yaml
Labels: size/XL, ⚒️ infra

#26 [HOTFIX/#25] 속성 파일 인식 불가 이슈 해결 및 외부 파일 주입 방식 적용
  Dockerfile
  src/main/java/sopt/makers/authentication/external/oauth/AppleAuthService.java
  src/main/java/sopt/makers/authentication/external/oauth/GoogleAuthService.java
  src/main/java/sopt/makers/authentication/support/config/ApplicationConfig.java
  src/main/java/sopt/makers/authentication/support/config/SecurityConfig.java
  src/main/java/sopt/makers/authentication/support/constant/SystemConstant.java
  src/main/java/sopt/makers/authentication/support/security/filter/JwtAuthenticationFilter.java
  src/main/java/sopt/makers/authentication/support/value/AppleOAuthProperty.java
  src/main/java/sopt/makers/authentication/support/value/AuthProperty.java
  src/main/java/sopt/makers/authentication/support/value/GoogleOAuthProperty.java
  src/main/resources/external.yaml
Labels: 🔨 fix, size/L

#24 [FEAT/#23] 소셜 계정 변경하기 API 구현
  src/main/java/sopt/makers/authentication/application/auth/api/AuthApiController.java
  src/main/java/sopt/makers/authentication/application/auth/api/SocialAccountApi.java
  src/main/java/sopt/makers/authentication/application/auth/api/SocialAccountApiController.java
  src/main/java/sopt/makers/authentication/application/auth/dto/request/AuthRequest.java
  src/main/java/sopt/makers/authentication/application/auth/dto/request/SocialAccountRequest.java
  src/main/java/sopt/makers/authentication/database/UserRepositoryImpl.java
  src/main/java/sopt/makers/authentication/database/rdb/entity/UserEntity.java
  src/main/java/sopt/makers/authentication/database/rdb/repository/UserRegister.java
  src/main/java/sopt/makers/authentication/database/rdb/repository/UserRetriever.java
  src/main/java/sopt/makers/authentication/external/oauth/OAuthAuthenticatorImpl.java
  src/main/java/sopt/makers/authentication/support/code/domain/failure/UserFailure.java
  src/main/java/sopt/makers/authentication/support/code/domain/success/SocialAccountSuccess.java
  src/main/java/sopt/makers/authentication/support/util/KeyFileUtil.java
  src/main/java/sopt/makers/authentication/support/util/ResponseUtil.java
  src/main/java/sopt/makers/authentication/usecase/auth/port/in/AuthenticateSocialAccountUsecase.java
  src/main/java/sopt/makers/authentication/usecase/auth/port/in/UpdateSocialAccountUsecase.java
  src/main/java/sopt/makers/authentication/usecase/auth/port/out/OAuthAuthenticator.java
  src/main/java/sopt/makers/authentication/usecase/auth/port/out/UserRepository.java
  src/main/java/sopt/makers/authentication/usecase/auth/service/AuthenticateSocialAccountService.java
  src/main/java/sopt/makers/authentication/usecase/auth/service/UpdateSocialAccountService.java
Labels: 🎁 feature, size/L

#29 [REFACTOR/#28] 배포 방식 변경
  .dockerignore
  .github/workflows/cd-dev.yml
  appspec.yml
Labels: ⚒️ infra, size/L
