Repository sopt-makers/sopt-auth-backend, pull requests merged in 2024-11, with the labels that each got.

#2 [SETTING] 어플리케이션 이관
  .gitattributes
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  .github/release-drafter-config.yml
  .github/script/pre-commit
  .github/workflows/release-drafter.yml
  .gitignore
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.jar
  gradlew
  gradlew.bat
  settings.gradle.kts
  src/main/java/sopt/makers/authentication/AuthenticationApplication.java
  src/main/java/sopt/makers/authentication/application/auth/api/AuthApi.java
  src/main/java/sopt/makers/authentication/application/auth/api/AuthApiController.java
  src/main/java/sopt/makers/authentication/application/auth/dto/request/AuthRequest.java
  src/main/java/sopt/makers/authentication/application/auth/dto/response/AuthResponse.java
  src/main/java/sopt/makers/authentication/database/entity/PhoneVerification.java
  src/main/java/sopt/makers/authentication/database/repository/VerificationRepositoryImpl.java
  src/main/java/sopt/makers/authentication/domain/auth/PhoneVerification.java
  src/main/java/sopt/makers/authentication/domain/auth/RegisterInformation.java
  src/main/java/sopt/makers/authentication/support/common/api/BaseResponse.java
  src/main/java/sopt/makers/authentication/support/common/code/base/BaseCode.java
  src/main/java/sopt/makers/authentication/support/common/code/base/FailureCode.java
  src/main/java/sopt/makers/authentication/support/common/code/base/SuccessCode.java
  src/main/java/sopt/makers/authentication/support/common/code/failure/AuthFailure.java
  src/main/java/sopt/makers/authentication/support/common/code/failure/TokenFailure.java
  src/main/java/sopt/makers/authentication/support/common/exception/AuthException.java
  src/main/java/sopt/makers/authentication/support/common/exception/TokenException.java
  src/main/java/sopt/makers/authentication/support/common/exception/base/BaseException.java
  src/main/java/sopt/makers/authentication/support/config/ApplicationConfig.java
  src/main/java/sopt/makers/authentication/support/config/JpaConfig.java
  src/main/java/sopt/makers/authentication/support/config/SecurityConfig.java
  src/main/java/sopt/makers/authentication/support/constant/SystemConstant.java
  src/main/java/sopt/makers/authentication/support/jwt/JwtProvider.java
  src/main/java/sopt/makers/authentication/support/jwt/provider/JwtAuthTokenProvider.java
  src/main/java/sopt/makers/authentication/support/security/authentication/CustomAuthentication.java
  src/main/java/sopt/makers/authentication/support/security/filter/JwtAuthenticationFilter.java
  src/main/java/sopt/makers/authentication/support/security/filter/JwtExceptionFilter.java
  src/main/java/sopt/makers/authentication/support/util/ResponseUtil.java
  src/main/java/sopt/makers/authentication/support/value/AuthProperty.java
  src/main/java/sopt/makers/authentication/support/value/GabiaProperty.java
  src/main/java/sopt/makers/authentication/support/value/JwtProperty.java
  src/main/java/sopt/makers/authentication/support/value/MakersProperty.java
  src/main/java/sopt/makers/authentication/usecase/auth/port/in/CreateVerificationUsecase.java
  src/main/java/sopt/makers/authentication/usecase/auth/port/out/VerificationRepository.java
  src/main/java/sopt/makers/authentication/usecase/auth/service/CreateVerificationService.java
  src/main/resources/application-dev.yaml
  src/main/resources/application-local.yaml
  src/main/resources/application-prod.yaml
  src/main/resources/application-test.yaml
  src/main/resources/external.yaml
  src/main/resources/jpa.yaml
  src/main/resources/jwt.yaml
  src/test/java/sopt/makers/authentication/AuthenticationApplicationTests.java
Labels: size/XXL, ⚙️ setting

#6 [FEAT/#5] 도메인 불변 객체 이관 및 공통 엔티티 구현
  build.gradle.kts
  src/main/java/sopt/makers/authentication/AuthenticationApplication.java
  src/main/java/sopt/makers/authentication/database/cache/info.txt
  src/main/java/sopt/makers/authentication/database/core/common/BaseTimeEntity.java
  src/main/java/sopt/makers/authentication/database/core/entity/PhoneVerification.java
  src/main/java/sopt/makers/authentication/database/core/entity/UserActivityHistoryEntity.java
  src/main/java/sopt/makers/authentication/database/core/entity/UserEntity.java
  src/main/java/sopt/makers/authentication/database/core/entity/UserRegisterInfoEntity.java
  src/main/java/sopt/makers/authentication/database/core/repository/VerificationRepositoryImpl.java
  src/main/java/sopt/makers/authentication/domain/auth/Activity.java
  src/main/java/sopt/makers/authentication/domain/auth/ActivityList.java
  src/main/java/sopt/makers/authentication/domain/auth/AuthPlatform.java
  src/main/java/sopt/makers/authentication/domain/auth/Part.java
  src/main/java/sopt/makers/authentication/domain/auth/Profile.java
  src/main/java/sopt/makers/authentication/domain/auth/Role.java
  src/main/java/sopt/makers/authentication/domain/auth/SocialAccount.java
  src/main/java/sopt/makers/authentication/domain/auth/Team.java
  src/main/java/sopt/makers/authentication/domain/auth/User.java
  src/main/java/sopt/makers/authentication/support/common/code/failure/DomainFailure.java
  src/main/java/sopt/makers/authentication/support/common/exception/DomainException.java
  src/main/java/sopt/makers/authentication/support/config/JpaConfig.java
  src/main/resources/jpa.yaml
Labels: size/XL, 🎁 feature

#13 [FIX] 엔티티 식별 오류 해결
  .gitignore
  src/main/java/sopt/makers/authentication/support/config/JpaConfig.java
  src/main/resources/application-local.yaml
Labels: 🔨 fix, size/XS

#14 [FEAT] 소셜 로그인 구현
  .gitignore
  build.gradle.kts
  src/main/java/sopt/makers/authentication/external/oauth/AppleAuthService.java
  src/main/java/sopt/makers/authentication/external/oauth/GoogleAuthService.java
  src/main/java/sopt/makers/authentication/external/oauth/OAuthAuthenticatorImpl.java
  src/main/java/sopt/makers/authentication/external/oauth/OAuthService.java
  src/main/java/sopt/makers/authentication/external/oauth/dto/IdTokenResponse.java
  src/main/java/sopt/makers/authentication/support/code/external/failure/ClientError.java
  src/main/java/sopt/makers/authentication/support/config/ApplicationConfig.java
  src/main/java/sopt/makers/authentication/support/config/GsonConfig.java
  src/main/java/sopt/makers/authentication/support/config/OkHttpClientConfig.java
  src/main/java/sopt/makers/authentication/support/constant/OAuthConstant.java
  src/main/java/sopt/makers/authentication/support/util/KeyFileUtil.java
  src/main/java/sopt/makers/authentication/support/value/AppleProperty.java
  src/main/java/sopt/makers/authentication/support/value/GoogleProperty.java
  src/main/java/sopt/makers/authentication/usecase/auth/port/in/AuthenticateSocialAccountUsecase.java
  src/main/java/sopt/makers/authentication/usecase/auth/port/out/OAuthAuthenticator.java
  src/main/java/sopt/makers/authentication/usecase/auth/service/AuthenticateSocialAccountService.java
  src/main/resources/external.yaml
Labels: size/XL, 🎁 feature

#19 [FEAT/#18] 소셜 로그인 유즈케이스 구현
  src/main/java/sopt/makers/authentication/application/auth/api/AuthApi.java
  src/main/java/sopt/makers/authentication/application/auth/api/AuthApiController.java
  src/main/java/sopt/makers/authentication/application/auth/dto/request/AuthRequest.java
  src/main/java/sopt/makers/authentication/application/auth/dto/response/AuthResponse.java
  src/main/java/sopt/makers/authentication/database/UserRepositoryImpl.java
  src/main/java/sopt/makers/authentication/database/rdb/repository/UserJpaRepository.java
  src/main/java/sopt/makers/authentication/database/rdb/repository/UserRetriever.java
  src/main/java/sopt/makers/authentication/support/code/domain/failure/AuthFailure.java
  src/main/java/sopt/makers/authentication/support/code/domain/success/AuthSuccess.java
  src/main/java/sopt/makers/authentication/support/constant/JwtConstant.java
  src/main/java/sopt/makers/authentication/support/constant/OAuthConstant.java
  src/main/java/sopt/makers/authentication/support/constant/SystemConstant.java
  src/main/java/sopt/makers/authentication/support/util/CookieUtil.java
  src/main/java/sopt/makers/authentication/usecase/auth/port/in/AuthenticateSocialAccountUsecase.java
  src/main/java/sopt/makers/authentication/usecase/auth/port/out/UserRepository.java
  src/main/java/sopt/makers/authentication/usecase/auth/service/AuthenticateSocialAccountService.java
Labels: 🎁 feature, size/L
