Repository sopt-makers/sopt-auth-backend, pull requests merged in 2025-07, with the labels that each got.

#128 [FIX] request로 전달된 이름 및 전화번호가 아닌 인증 이력에 저장된 정보를 바탕으로 이름, 전화번호를 전달하도록 수정
  src/main/java/sopt/makers/authentication/adapter/in/web/dto/auth/request/AuthRequest.java
  src/main/java/sopt/makers/authentication/application/port/in/auth/VerifyPhoneVerificationUsecase.java
  src/main/java/sopt/makers/authentication/application/service/auth/VerifyVerificationService.java
  src/main/java/sopt/makers/authentication/domain/auth/PhoneVerification.java
Labels: 🔨 fix, size/M

#131 [FEAT/#130] 인증코드 생성 및 인증에 애플 심사 매직 넘버 로직 추가
  src/main/java/sopt/makers/authentication/adapter/out/external/oauth/MagicLoginProperty.java
  src/main/java/sopt/makers/authentication/application/port/in/auth/CreatePhoneVerificationUsecase.java
  src/main/java/sopt/makers/authentication/application/service/auth/CreateVerificationService.java
  src/main/java/sopt/makers/authentication/application/service/auth/VerifyVerificationService.java
  src/main/java/sopt/makers/authentication/config/ApplicationConfig.java
  src/main/resources/application-dev.yaml
  src/main/resources/application-local.yaml
  src/main/resources/application-prod.yaml
  src/main/resources/application-test.yaml
  src/main/resources/external.yaml
Labels: 🎁 feature, size/M

#137 [FEAT] 매직 넘버 심사를 위한 회원가입 로직에 관련 로직 추가
  src/main/java/sopt/makers/authentication/application/service/auth/SignUpService.java
Labels: 🎁 feature, size/M

#138 [FEAT/#135] 유저 조회에 name, team 조건 및 페이지네이션 추가
  src/main/java/sopt/makers/authentication/adapter/in/web/controller/user/UserApi.java
  src/main/java/sopt/makers/authentication/adapter/in/web/controller/user/UserApiController.java
  src/main/java/sopt/makers/authentication/adapter/in/web/dto/user/response/UserResponse.java
  src/main/java/sopt/makers/authentication/adapter/out/persistence/repository/user/UserJpaRepository.java
  src/main/java/sopt/makers/authentication/adapter/out/persistence/repository/user/UserRepositoryImpl.java
  src/main/java/sopt/makers/authentication/adapter/out/persistence/repository/user/UserRetriever.java
  src/main/java/sopt/makers/authentication/application/port/in/user/GetUserProfileUsecase.java
  src/main/java/sopt/makers/authentication/application/port/out/user/UserRepository.java
  src/main/java/sopt/makers/authentication/application/service/user/GetUserProfileService.java
  src/main/java/sopt/makers/authentication/application/validator/user/UserSearchConditionValidator.java
  src/main/java/sopt/makers/authentication/common/constant/PagingConstant.java
  src/main/java/sopt/makers/authentication/domain/user/UserOrderBy.java
Labels: 🎁 feature, size/L
