Repository sopt-makers/sopt-auth-backend, pull requests merged in 2025-04, with the labels that each got.

#61 [FEAT/#52] x-api-key 헤더 검증 플로우 구현
  src/main/java/sopt/makers/authentication/application/auth/api/AuthKeyApiController.java
  src/main/java/sopt/makers/authentication/support/code/domain/failure/AuthFailure.java
  src/main/java/sopt/makers/authentication/support/config/ApplicationConfig.java
  src/main/java/sopt/makers/authentication/support/config/LocalRSAKeyManager.java
  src/main/java/sopt/makers/authentication/support/config/SecurityConfig.java
  src/main/java/sopt/makers/authentication/support/jwt/provider/JwtAuthAccessTokenProvider.java
  src/main/java/sopt/makers/authentication/support/jwt/provider/JwtAuthRefreshTokenProvider.java
  src/main/java/sopt/makers/authentication/support/jwt/token/JwtAccessToken.java
  src/main/java/sopt/makers/authentication/support/security/authentication/ApiKeyAuthentication.java
  src/main/java/sopt/makers/authentication/support/security/filter/ApiKeyAuthenticationFilter.java
  src/main/java/sopt/makers/authentication/support/security/filter/AuthenticationExceptionFilter.java
  src/main/java/sopt/makers/authentication/support/security/filter/JwtAuthenticationFilter.java
  src/main/java/sopt/makers/authentication/support/util/CookieUtil.java
  src/main/java/sopt/makers/authentication/support/value/AppleOAuthProperty.java
  src/main/java/sopt/makers/authentication/support/value/GoogleOAuthProperty.java
  src/main/java/sopt/makers/authentication/support/value/JwtProperty.java
  src/main/java/sopt/makers/authentication/support/value/MakersProperty.java
  src/main/java/sopt/makers/authentication/support/value/SecurityProperty.java
  src/main/java/sopt/makers/authentication/usecase/auth/service/JwksRetrieveService.java
  src/main/resources/application-dev.yaml
  src/main/resources/application-local.yaml
  src/main/resources/application-prod.yaml
  src/main/resources/application-test.yaml
  src/main/resources/external.yaml
  src/main/resources/jwt.yaml
  src/main/resources/security.yaml
  src/test/java/sopt/makers/authentication/jwt/JwtAccessTokenTest.java
  src/test/java/sopt/makers/authentication/jwt/JwtPropertyTest.java
  src/test/java/sopt/makers/authentication/support/value/SecurityPropertyTest.java
Labels: 🎁 feature, size/L

#66 [FEAT/#65] 문자 인증 비동기 처리
  src/main/java/sopt/makers/authentication/application/auth/event/PhoneVerificationEventListener.java
  src/main/java/sopt/makers/authentication/domain/auth/PhoneVerificationCreatedEvent.java
  src/main/java/sopt/makers/authentication/support/config/AsyncConfig.java
  src/main/java/sopt/makers/authentication/usecase/auth/service/CreateVerificationService.java
  src/test/java/sopt/makers/authentication/usecase/auth/service/CreateVerificationServiceTest.java
Labels: 🎁 feature, size/M

#64 [FIX/#43] 전화번호 인증 예외케이스 세분화 처리
  src/main/java/sopt/makers/authentication/application/auth/event/PhoneVerificationEventListener.java
  src/main/java/sopt/makers/authentication/database/rdb/repository/phone/verification/PhoneVerificationJpaRepository.java
  src/main/java/sopt/makers/authentication/database/rdb/repository/phone/verification/PhoneVerificationRepositoryImpl.java
  src/main/java/sopt/makers/authentication/database/rdb/repository/phone/verification/PhoneVerificationRetriever.java
  src/main/java/sopt/makers/authentication/database/rdb/repository/user/UserJpaRepository.java
  src/main/java/sopt/makers/authentication/database/rdb/repository/user/UserRepositoryImpl.java
  src/main/java/sopt/makers/authentication/database/rdb/repository/user/UserRetriever.java
  src/main/java/sopt/makers/authentication/database/rdb/repository/user/register/UserRegisterInfoRepositoryImpl.java
  src/main/java/sopt/makers/authentication/database/rdb/repository/user/register/UserRegisterInfoRetriever.java
  src/main/java/sopt/makers/authentication/domain/auth/PhoneVerificationCreatedEvent.java
  src/main/java/sopt/makers/authentication/support/code/domain/failure/AuthFailure.java
  src/main/java/sopt/makers/authentication/support/code/domain/failure/UserFailure.java
  src/main/java/sopt/makers/authentication/usecase/auth/port/out/PhoneVerificationRepository.java
  src/main/java/sopt/makers/authentication/usecase/auth/port/out/UserRepository.java
  src/main/java/sopt/makers/authentication/usecase/auth/service/CreateVerificationService.java
  src/main/java/sopt/makers/authentication/usecase/auth/service/SignUpService.java
  src/main/java/sopt/makers/authentication/usecase/auth/service/VerifyVerificationService.java
  src/main/java/sopt/makers/authentication/usecase/user/port/out/UserRegisterInfoRepository.java
  src/test/java/sopt/makers/authentication/database/PhoneVerificationRepositoryImplTest.java
  src/test/java/sopt/makers/authentication/usecase/auth/service/CreateVerificationServiceTest.java
  src/test/java/sopt/makers/authentication/usecase/auth/service/SignUpServiceTest.java
  src/test/java/sopt/makers/authentication/usecase/auth/service/VerifyVerificationServiceTest.java
Labels: 🔨 fix, size/L

#63 [FIX/#62] 로그인시 유저 Activity role도 함께 조회하도록 수정
  build.gradle.kts
  src/main/java/sopt/makers/authentication/database/rdb/repository/user/UserJpaRepository.java
  src/main/java/sopt/makers/authentication/database/rdb/repository/user/activity/UserActivityHistoryJpaRepository.java
  src/main/java/sopt/makers/authentication/database/rdb/repository/user/activity/UserActivityHistoryRepositoryImpl.java
  src/main/java/sopt/makers/authentication/database/rdb/repository/user/activity/UserActivityHistoryRetriever.java
  src/main/java/sopt/makers/authentication/domain/user/ActivityList.java
  src/main/java/sopt/makers/authentication/support/jwt/provider/JwtAuthAccessTokenProvider.java
  src/main/java/sopt/makers/authentication/support/jwt/provider/JwtAuthRefreshTokenProvider.java
  src/main/java/sopt/makers/authentication/usecase/auth/service/AuthenticateSocialAccountService.java
  src/main/java/sopt/makers/authentication/usecase/user/port/out/UserActivityHistoryRepository.java
  src/test/java/sopt/makers/authentication/jwt/JwtAccessTokenTest.java
  src/test/java/sopt/makers/authentication/jwt/JwtRefreshTokenTest.java
Labels: 🔨 fix, size/M

#70 [FEAT/#69] 모니터링 설정 구축
  build.gradle.kts
  src/main/java/sopt/makers/authentication/support/config/SecurityConfig.java
  src/main/java/sopt/makers/authentication/support/constant/SystemConstant.java
  src/main/java/sopt/makers/authentication/support/security/authentication/ApiKeyAuthentication.java
  src/main/java/sopt/makers/authentication/support/security/filter/ApiKeyAuthenticationFilter.java
  src/main/java/sopt/makers/authentication/support/value/SecurityProperty.java
  src/main/resources/application-dev.yaml
  src/main/resources/application-local.yaml
  src/main/resources/application-prod.yaml
  src/main/resources/monitoring.yaml
  src/main/resources/security.yaml
  src/test/java/sopt/makers/authentication/support/value/SecurityPropertyTest.java
Labels: 🎁 feature, size/L

#76 [FIX/#73] 웹 refresh 로직에서 Cookie로부터 refresh 토큰을 조회해오도록 수정
  src/main/java/sopt/makers/authentication/application/auth/api/AuthApiController.java
  src/main/java/sopt/makers/authentication/support/constant/JwtConstant.java
  src/main/java/sopt/makers/authentication/support/jwt/provider/JwtAuthRefreshTokenProvider.java
  src/test/java/sopt/makers/authentication/jwt/JwtRefreshTokenTest.java
Labels: 🔨 fix, size/M
