Repository sopt-makers/sopt-auth-backend, pull requests merged in 2025-05, with the labels that each got.

#79 [FEAT/#78] jwt 토큰 header에 kid가 포함되도록 변경
  src/main/java/sopt/makers/authentication/support/config/JwtRSAKeyConfiguration.java
  src/main/java/sopt/makers/authentication/support/jwt/JwtProvider.java
  src/main/java/sopt/makers/authentication/support/jwt/provider/JwtAuthAccessTokenProvider.java
  src/main/java/sopt/makers/authentication/support/jwt/provider/JwtAuthRefreshTokenProvider.java
  src/main/java/sopt/makers/authentication/usecase/auth/service/AuthenticateSocialAccountService.java
  src/test/java/sopt/makers/authentication/jwt/JwtAccessTokenTest.java
  src/test/java/sopt/makers/authentication/jwt/JwtRefreshTokenTest.java
Labels: 🎁 feature, size/M

#77 [FEAT/#74] 유저 정보 조회 API 구현
  src/main/java/sopt/makers/authentication/application/user/api/UserApi.java
  src/main/java/sopt/makers/authentication/application/user/api/UserApiController.java
  src/main/java/sopt/makers/authentication/application/user/dto/response/UserResponse.java
  src/main/java/sopt/makers/authentication/database/rdb/entity/UserEntity.java
  src/main/java/sopt/makers/authentication/database/rdb/repository/user/UserJpaRepository.java
  src/main/java/sopt/makers/authentication/database/rdb/repository/user/UserRepositoryImpl.java
  src/main/java/sopt/makers/authentication/database/rdb/repository/user/UserRetriever.java
  src/main/java/sopt/makers/authentication/database/rdb/repository/user/activity/UserActivityHistoryJpaRepository.java
  src/main/java/sopt/makers/authentication/domain/user/Activity.java
  src/main/java/sopt/makers/authentication/domain/user/Part.java
  src/main/java/sopt/makers/authentication/domain/user/Team.java
  src/main/java/sopt/makers/authentication/support/code/domain/failure/UserFailure.java
  src/main/java/sopt/makers/authentication/support/code/domain/success/UserSuccess.java
  src/main/java/sopt/makers/authentication/support/jwt/service/JwtAuthAccessTokenService.java
  src/main/java/sopt/makers/authentication/support/jwt/service/JwtAuthRefreshTokenService.java
  src/main/java/sopt/makers/authentication/support/security/filter/JwtAuthenticationFilter.java
  src/main/java/sopt/makers/authentication/support/validator/UserIdValidator.java
  src/main/java/sopt/makers/authentication/usecase/auth/service/AuthenticateSocialAccountService.java
  src/main/java/sopt/makers/authentication/usecase/auth/service/CreateVerificationService.java
  src/main/java/sopt/makers/authentication/usecase/auth/service/SignUpService.java
  src/main/java/sopt/makers/authentication/usecase/auth/service/UpdateSocialAccountService.java
  src/main/java/sopt/makers/authentication/usecase/user/port/in/GetUserInformationUsecase.java
  src/main/java/sopt/makers/authentication/usecase/user/port/out/UserRepository.java
  src/main/java/sopt/makers/authentication/usecase/user/service/GetSocialAccountPlatformService.java
  src/main/java/sopt/makers/authentication/usecase/user/service/GetUserInformationService.java
  src/main/resources/security.yaml
  src/test/java/sopt/makers/authentication/jwt/JwtAccessTokenTest.java
  src/test/java/sopt/makers/authentication/jwt/JwtRefreshTokenTest.java
  src/test/java/sopt/makers/authentication/usecase/auth/service/CreateVerificationServiceTest.java
  src/test/java/sopt/makers/authentication/usecase/auth/service/GetSocialAccountPlatformServiceTest.java
  src/test/java/sopt/makers/authentication/usecase/auth/service/SignUpServiceTest.java
Labels: 🎁 feature, size/L

#82 [FEAT/#81] apple aud 필드를 web/app 분리하여 관리하도록 변경
  src/main/java/sopt/makers/authentication/external/oauth/AppleAuthService.java
  src/main/java/sopt/makers/authentication/support/value/AppleOAuthProperty.java
  src/main/resources/external.yaml
Labels: 🎁 feature, size/S

#84 [FIX/83] UserEntity를 유저 도메인으로 변환시, userActivityHistoryList가 null 또는 비어…
  src/main/java/sopt/makers/authentication/database/rdb/entity/UserEntity.java
Labels: size/XS

#87 [INFRA/#85] 배포 스크립트 github로 관리할 수 있도록 분리 및 docker compose 도입
  .github/workflows/cd-dev.yml
  .github/workflows/ci.yml
  docker-compose.yml
  scripts/check_running_container.sh
  scripts/deploy.sh
  scripts/health_check.sh
  scripts/pull_and_run_container.sh
  scripts/reload_nginx.sh
  scripts/stop_and_clean_container.sh
Labels: size/L

#89 [FIX] cd-dev.yml에 /scripts/*.sh 파일들에 실행 권한 부여
  .github/workflows/cd-dev.yml
Labels: 🔨 fix, size/XS

#91 [INFRA/#90] docker-compose.yml에 env_file 경로 추가
  docker-compose.yml
Labels: size/XS

#93 [FIX] health_check.sh: actuator 경로 앞 슬래시 삭제
  scripts/health_check.sh
Labels: 🔨 fix, size/XS

#95 [FIX/#94] check_running_container: 현재 동작 중인 컨테이너의 port를 식별하는 로직을 수정
  scripts/check_running_container.sh
Labels: 🔨 fix, size/S

#96 [FEAT/#80] 유저 정보 수정 API 구현
  src/main/java/sopt/makers/authentication/application/user/api/UserApi.java
  src/main/java/sopt/makers/authentication/application/user/api/UserApiController.java
  src/main/java/sopt/makers/authentication/application/user/dto/request/UserRequest.java
  src/main/java/sopt/makers/authentication/application/user/dto/response/UserResponse.java
  src/main/java/sopt/makers/authentication/database/rdb/repository/user/UserRepositoryImpl.java
  src/main/java/sopt/makers/authentication/database/rdb/repository/user/UserRetriever.java
  src/main/java/sopt/makers/authentication/database/rdb/repository/user/activity/UserActivityHistoryRegister.java
  src/main/java/sopt/makers/authentication/database/rdb/repository/user/activity/UserActivityHistoryRepositoryImpl.java
  src/main/java/sopt/makers/authentication/domain/user/Part.java
  src/main/java/sopt/makers/authentication/domain/user/Profile.java
  src/main/java/sopt/makers/authentication/domain/user/Team.java
  src/main/java/sopt/makers/authentication/domain/user/User.java
  src/main/java/sopt/makers/authentication/support/code/domain/failure/UserFailure.java
  src/main/java/sopt/makers/authentication/support/code/domain/success/UserSuccess.java
  src/main/java/sopt/makers/authentication/support/validator/UserIdValidator.java
  src/main/java/sopt/makers/authentication/usecase/user/port/in/GetUserProfileUsecase.java
  src/main/java/sopt/makers/authentication/usecase/user/port/in/UpdateUserProfileUsecase.java
  src/main/java/sopt/makers/authentication/usecase/user/port/out/UserActivityHistoryRepository.java
  src/main/java/sopt/makers/authentication/usecase/user/port/out/UserRepository.java
  src/main/java/sopt/makers/authentication/usecase/user/service/GetUserProfileService.java
  src/main/java/sopt/makers/authentication/usecase/user/service/UpdateUserProfileService.java
  src/test/java/sopt/makers/authentication/usecase/user/service/UpdateUserProfileServiceTest.java
Labels: 🎁 feature, size/L

#99 [FIX] 유저 정보 조회 response에 latestGeneration 포함하도록 수정
  src/main/java/sopt/makers/authentication/application/user/dto/response/UserResponse.java
  src/main/java/sopt/makers/authentication/usecase/user/port/in/GetUserProfileUsecase.java
Labels: 🔨 fix, size/XS
