Repository sopt-makers/sopt-auth-backend, pull requests merged in 2025-01, with the labels that each got.

#27 [FEAT/#17] 가입 계정 플랫폼 조회 기능 구현
  src/main/java/sopt/makers/authentication/application/auth/api/AuthApiController.java
  src/main/java/sopt/makers/authentication/application/auth/api/SocialAccountApi.java
  src/main/java/sopt/makers/authentication/application/auth/api/SocialAccountApiController.java
  src/main/java/sopt/makers/authentication/application/auth/dto/response/AuthResponse.java
  src/main/java/sopt/makers/authentication/support/code/domain/success/AuthSuccess.java
  src/main/java/sopt/makers/authentication/support/code/domain/success/SocialAccountSuccess.java
  src/main/java/sopt/makers/authentication/support/constant/SystemConstant.java
  src/main/java/sopt/makers/authentication/support/security/filter/JwtAuthenticationFilter.java
  src/main/java/sopt/makers/authentication/usecase/auth/port/in/GetSocialAccountUsecase.java
  src/main/java/sopt/makers/authentication/usecase/auth/service/GetSocialAccountPlatformService.java
  src/main/resources/jpa.yaml
  src/test/java/sopt/makers/authentication/usecase/auth/service/GetSocialAccountPlatformServiceTest.java
Labels: 🎁 feature, size/L

#30 [FEAT/#16] 회원가입 API 구현
  src/main/java/sopt/makers/authentication/application/auth/api/AuthApi.java
  src/main/java/sopt/makers/authentication/application/auth/api/AuthApiController.java
  src/main/java/sopt/makers/authentication/application/auth/dto/request/AuthRequest.java
  src/main/java/sopt/makers/authentication/database/UserRegisterInfoRepositoryImpl.java
  src/main/java/sopt/makers/authentication/database/UserRepositoryImpl.java
  src/main/java/sopt/makers/authentication/database/rdb/entity/UserRegisterInfoEntity.java
  src/main/java/sopt/makers/authentication/database/rdb/repository/UserRegisterInfoRemover.java
  src/main/java/sopt/makers/authentication/domain/user/UserRegisterInfo.java
  src/main/java/sopt/makers/authentication/external/oauth/AppleAuthService.java
  src/main/java/sopt/makers/authentication/external/oauth/GoogleAuthService.java
  src/main/java/sopt/makers/authentication/external/oauth/OAuthAuthenticatorImpl.java
  src/main/java/sopt/makers/authentication/external/oauth/client/AppleAuthClient.java
  src/main/java/sopt/makers/authentication/external/oauth/client/GoogleAuthClient.java
  src/main/java/sopt/makers/authentication/support/code/domain/failure/AuthFailure.java
  src/main/java/sopt/makers/authentication/support/code/domain/success/AuthSuccess.java
  src/main/java/sopt/makers/authentication/support/code/external/failure/ClientError.java
  src/main/java/sopt/makers/authentication/support/code/support/failure/TokenFailure.java
  src/main/java/sopt/makers/authentication/support/constant/OAuthConstant.java
  src/main/java/sopt/makers/authentication/support/util/RequestUtil.java
  src/main/java/sopt/makers/authentication/usecase/auth/port/in/SignUpUsecase.java
  src/main/java/sopt/makers/authentication/usecase/auth/port/out/OAuthAuthenticator.java
  src/main/java/sopt/makers/authentication/usecase/auth/port/out/UserRepository.java
  src/main/java/sopt/makers/authentication/usecase/auth/service/SignUpService.java
  src/main/java/sopt/makers/authentication/usecase/user/port/out/UserRegisterInfoRepository.java
Labels: size/XL, 🎁 feature

#34 [FEAT/#33] 소셜 로그인, 계정 변경하기 API의 oauth 인증 과정 변경
  src/main/java/sopt/makers/authentication/application/auth/dto/request/AuthRequest.java
  src/main/java/sopt/makers/authentication/application/auth/dto/request/SocialAccountRequest.java
  src/main/java/sopt/makers/authentication/database/rdb/entity/UserEntity.java
  src/main/java/sopt/makers/authentication/domain/auth/SocialAccount.java
  src/main/java/sopt/makers/authentication/external/oauth/AppleAuthService.java
  src/main/java/sopt/makers/authentication/external/oauth/GoogleAuthService.java
  src/main/java/sopt/makers/authentication/external/oauth/OAuthAuthenticatorImpl.java
  src/main/java/sopt/makers/authentication/external/oauth/OAuthService.java
  src/main/java/sopt/makers/authentication/external/oauth/client/AppleAuthClient.java
  src/main/java/sopt/makers/authentication/external/oauth/client/GoogleAuthClient.java
  src/main/java/sopt/makers/authentication/external/oauth/dto/IdTokenResponse.java
  src/main/java/sopt/makers/authentication/support/code/external/failure/ClientError.java
  src/main/java/sopt/makers/authentication/support/constant/OAuthConstant.java
  src/main/java/sopt/makers/authentication/usecase/auth/port/in/AuthenticateSocialAccountUsecase.java
  src/main/java/sopt/makers/authentication/usecase/auth/port/in/UpdateSocialAccountUsecase.java
  src/main/java/sopt/makers/authentication/usecase/auth/port/out/OAuthAuthenticator.java
  src/main/java/sopt/makers/authentication/usecase/auth/service/AuthenticateSocialAccountService.java
  src/main/java/sopt/makers/authentication/usecase/auth/service/SignUpService.java
  src/main/java/sopt/makers/authentication/usecase/auth/service/UpdateSocialAccountService.java
Labels: 🎁 feature, size/L

#32 [FEAT/#31] 토큰 Refresh API 구현
  src/main/java/sopt/makers/authentication/application/auth/api/AuthApi.java
  src/main/java/sopt/makers/authentication/application/auth/api/AuthApiController.java
  src/main/java/sopt/makers/authentication/application/auth/dto/request/AuthRequest.java
  src/main/java/sopt/makers/authentication/support/jwt/provider/JwtAuthAccessTokenProvider.java
  src/main/java/sopt/makers/authentication/usecase/auth/port/in/AuthenticateSocialAccountUsecase.java
  src/main/java/sopt/makers/authentication/usecase/auth/service/AuthenticateSocialAccountService.java
Labels: 🎁 feature, size/M

#36 [DOCS/#35] README 작성
  README.md
Labels: 📋 docs, size/L

#38 [FIX] RequestBody 어노테이션 누락 수정
  src/main/java/sopt/makers/authentication/application/auth/api/AuthApiController.java
Labels: 🔨 fix, size/XS

#40 [FIX] jwtAuthenticationFilter의 검증 로직 수정
  src/main/java/sopt/makers/authentication/support/security/filter/JwtAuthenticationFilter.java
Labels: 🔨 fix, size/XS

#42 [FIX/#41] JWT 필터 내 whilelist 처리 오류 해결
  src/main/java/sopt/makers/authentication/support/code/support/failure/CommonFailure.java
  src/main/java/sopt/makers/authentication/support/constant/SystemConstant.java
  src/main/java/sopt/makers/authentication/support/exception/ApplicationExceptionHandler.java
  src/main/java/sopt/makers/authentication/support/security/filter/JwtAuthenticationFilter.java
Labels: 🔨 fix, size/M

#45 [FIX/#44] GoogleAuthService - ClassCastException 오류 수정
  src/main/java/sopt/makers/authentication/external/oauth/GoogleAuthService.java
Labels: size/XS
