Repository sopt-makers/sopt-auth-backend, pull requests merged in 2025-08, with the labels that each got.

#146 [FIX/#145] 토큰 리프레시 시 Access token이 만료되어도 재발급 가능하도록 수정
  src/main/java/sopt/makers/authentication/adapter/out/jwt/decoder/LenientJwtDecoder.java
  src/main/java/sopt/makers/authentication/adapter/out/jwt/service/JwtAuthAccessTokenService.java
  src/main/java/sopt/makers/authentication/adapter/out/jwt/service/JwtAuthRefreshTokenService.java
  src/main/java/sopt/makers/authentication/application/service/auth/AuthenticateSocialAccountService.java
  src/main/java/sopt/makers/authentication/config/JwtRSAKeyConfiguration.java
Labels: 🔨 fix, size/M

#152 [FIX] AuthApi interface 어노테이션 불일치 문제 해결을 위해 어노테이션 삭제
  src/main/java/sopt/makers/authentication/adapter/in/web/controller/auth/AuthApi.java
Labels: 🔨 fix, size/XS

#158 [FIX/#157] 유저 조회 시 필터 최소 입력 조건 제거
  src/main/java/sopt/makers/authentication/adapter/in/web/controller/user/UserApiController.java
  src/main/java/sopt/makers/authentication/application/validator/user/UserSearchConditionValidator.java
Labels: 🔨 fix, size/S

#162 [REFACTOR/#161] 등록되지 않은 회원이 회원가입 시도 할 때의 에러메시지 수정
  src/main/java/sopt/makers/authentication/domain/auth/exception/AuthFailure.java
Labels: 🧼 refactor, size/XS

#165 [Feat/#163] 회원가입 시 플그 default 컬럼 추가 로직 구현
  src/main/java/sopt/makers/authentication/adapter/out/external/exception/ClientError.java
  src/main/java/sopt/makers/authentication/adapter/out/external/playground/PlaygroundClient.java
  src/main/java/sopt/makers/authentication/adapter/out/external/playground/PlaygroundProperty.java
  src/main/java/sopt/makers/authentication/adapter/out/external/sms/GabiaClient.java
  src/main/java/sopt/makers/authentication/adapter/out/jwt/LocalRSAKeyManager.java
  src/main/java/sopt/makers/authentication/adapter/out/persistence/repository/phone/verification/PhoneVerificationRepositoryImpl.java
  src/main/java/sopt/makers/authentication/adapter/out/persistence/repository/phone/verification/PhoneVerificationRetriever.java
  src/main/java/sopt/makers/authentication/application/port/out/auth/PhoneVerificationRepository.java
  src/main/java/sopt/makers/authentication/application/service/auth/SignUpService.java
  src/main/java/sopt/makers/authentication/application/service/auth/UpdateSocialAccountService.java
  src/main/java/sopt/makers/authentication/application/service/user/GetSocialAccountPlatformService.java
  src/main/java/sopt/makers/authentication/application/service/user/UpdateUserProfileService.java
  src/main/java/sopt/makers/authentication/application/validator/auth/PhoneVerificationValidator.java
  src/main/java/sopt/makers/authentication/config/ApplicationConfig.java
  src/main/resources/external.yaml
Labels: 🎁 feature, size/L

#168 [FIX] FACEBOOK을 AuthPlatform에 추가
  src/main/java/sopt/makers/authentication/adapter/out/external/oauth/OAuthAuthenticatorImpl.java
  src/main/java/sopt/makers/authentication/application/service/auth/SignUpService.java
  src/main/java/sopt/makers/authentication/domain/auth/AuthPlatform.java
Labels: 🔨 fix, size/XS

#170 [Fix/#169] 플레이그라운드 더블 슬래시 이슈 수정
  src/main/java/sopt/makers/authentication/adapter/out/external/playground/PlaygroundClient.java
Labels: 🔨 fix, size/XS

#172 [DEPLOY] v1.1.1
  src/main/java/sopt/makers/authentication/adapter/out/external/exception/ClientError.java
  src/main/java/sopt/makers/authentication/adapter/out/external/oauth/OAuthAuthenticatorImpl.java
  src/main/java/sopt/makers/authentication/adapter/out/external/playground/PlaygroundClient.java
  src/main/java/sopt/makers/authentication/adapter/out/external/playground/PlaygroundProperty.java
  src/main/java/sopt/makers/authentication/adapter/out/external/sms/GabiaClient.java
  src/main/java/sopt/makers/authentication/adapter/out/jwt/LocalRSAKeyManager.java
  src/main/java/sopt/makers/authentication/adapter/out/persistence/repository/phone/verification/PhoneVerificationRepositoryImpl.java
  src/main/java/sopt/makers/authentication/adapter/out/persistence/repository/phone/verification/PhoneVerificationRetriever.java
  src/main/java/sopt/makers/authentication/application/port/out/auth/PhoneVerificationRepository.java
  src/main/java/sopt/makers/authentication/application/service/auth/SignUpService.java
  src/main/java/sopt/makers/authentication/application/service/auth/UpdateSocialAccountService.java
  src/main/java/sopt/makers/authentication/application/service/user/GetSocialAccountPlatformService.java
  src/main/java/sopt/makers/authentication/application/service/user/UpdateUserProfileService.java
  src/main/java/sopt/makers/authentication/application/validator/auth/PhoneVerificationValidator.java
  src/main/java/sopt/makers/authentication/config/ApplicationConfig.java
  src/main/java/sopt/makers/authentication/domain/auth/AuthPlatform.java
  src/main/java/sopt/makers/authentication/domain/auth/exception/AuthFailure.java
  src/main/resources/external.yaml
Labels: 🚀 deploy, ✨ patch, size/L
