Repository sopt-makers/sopt-auth-backend, pull requests merged in 2025-03, with the labels that each got.

#53 [REFACTOR/#51] 트랜잭션 처리 통일화 및 User 도메인에 id 필드 추가
  src/main/java/sopt/makers/authentication/database/rdb/entity/BaseEntity.java
  src/main/java/sopt/makers/authentication/database/rdb/entity/PhoneVerificationEntity.java
  src/main/java/sopt/makers/authentication/database/rdb/entity/UserActivityHistoryEntity.java
  src/main/java/sopt/makers/authentication/database/rdb/entity/UserEntity.java
  src/main/java/sopt/makers/authentication/database/rdb/repository/phone/verification/PhoneVerificationJpaRepository.java
  src/main/java/sopt/makers/authentication/database/rdb/repository/phone/verification/PhoneVerificationRegister.java
  src/main/java/sopt/makers/authentication/database/rdb/repository/phone/verification/PhoneVerificationRemover.java
  src/main/java/sopt/makers/authentication/database/rdb/repository/phone/verification/PhoneVerificationRepositoryImpl.java
  src/main/java/sopt/makers/authentication/database/rdb/repository/phone/verification/PhoneVerificationRetriever.java
  src/main/java/sopt/makers/authentication/database/rdb/repository/user/UserJpaRepository.java
  src/main/java/sopt/makers/authentication/database/rdb/repository/user/UserRegister.java
  src/main/java/sopt/makers/authentication/database/rdb/repository/user/UserRepositoryImpl.java
  src/main/java/sopt/makers/authentication/database/rdb/repository/user/UserRetriever.java
  src/main/java/sopt/makers/authentication/database/rdb/repository/user/register/UserRegisterInfoJpaRepository.java
  src/main/java/sopt/makers/authentication/database/rdb/repository/user/register/UserRegisterInfoRemover.java
  src/main/java/sopt/makers/authentication/database/rdb/repository/user/register/UserRegisterInfoRepositoryImpl.java
  src/main/java/sopt/makers/authentication/database/rdb/repository/user/register/UserRegisterInfoRetriever.java
  src/main/java/sopt/makers/authentication/domain/user/User.java
  src/main/java/sopt/makers/authentication/usecase/auth/port/out/UserRepository.java
  src/main/java/sopt/makers/authentication/usecase/auth/service/AuthenticateSocialAccountService.java
  src/main/java/sopt/makers/authentication/usecase/auth/service/SignUpService.java
  src/main/java/sopt/makers/authentication/usecase/auth/service/UpdateSocialAccountService.java
Labels: 🧼 refactor, size/L

#57 [FIX/#56] Apple 로그인 findMatchJWK 로직 수정
  src/main/java/sopt/makers/authentication/external/oauth/AppleAuthService.java
  src/main/java/sopt/makers/authentication/external/oauth/GoogleAuthService.java
Labels: size/S

#60 [REFACTOR/#59] yml에서 애플 sub 필드 삭제 및 aud 값 업데이트
  src/main/java/sopt/makers/authentication/database/rdb/entity/UserEntity.java
  src/main/resources/external.yaml
Labels: 🧼 refactor, size/XS

#58 [FIX/#48] SignUpService - 유저 기수 정보 저장하도록 수정
  src/main/java/sopt/makers/authentication/database/rdb/entity/UserEntity.java
  src/main/java/sopt/makers/authentication/database/rdb/repository/user/UserRepositoryImpl.java
  src/main/java/sopt/makers/authentication/database/rdb/repository/user/activity/UserActivityHistoryJpaRepository.java
  src/main/java/sopt/makers/authentication/database/rdb/repository/user/activity/UserActivityHistoryRegister.java
  src/main/java/sopt/makers/authentication/database/rdb/repository/user/activity/UserActivityHistoryRepositoryImpl.java
  src/main/java/sopt/makers/authentication/usecase/auth/port/out/UserRepository.java
  src/main/java/sopt/makers/authentication/usecase/auth/service/SignUpService.java
  src/main/java/sopt/makers/authentication/usecase/user/port/out/UserActivityHistoryRepository.java
  src/test/java/sopt/makers/authentication/usecase/auth/service/SignUpServiceTest.java
Labels: 🔨 fix, size/L
