Repository sopt-makers/sopt-auth-backend, pull requests merged in 2025-09, with the labels that each got.

#187 [FEAT] 유저 조회 응답에 role 필드 추가
  src/main/java/sopt/makers/authentication/adapter/in/web/dto/user/response/UserResponse.java
  src/main/java/sopt/makers/authentication/application/port/in/user/GetUserProfileUsecase.java
Labels: 🎁 feature, size/S

#193 [TEST] 회원가입 동시성 테스트를 위한 로직 추가
  src/main/java/sopt/makers/authentication/application/service/auth/CreateVerificationService.java
  src/main/java/sopt/makers/authentication/application/service/auth/SignUpService.java
Labels: size/M

#201 [DEPLOY] v1.1.6
  src/main/java/sopt/makers/authentication/domain/user/ActivityList.java
Labels: 🚀 deploy, ✨ patch, size/XS

#207 [FIX] 매직넘버 리턴값 code에서 phone으로 변경
  src/main/java/sopt/makers/authentication/application/service/auth/VerifyVerificationService.java
Labels: 🔨 fix, size/XS
